---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yanghl.
--- DateTime: 19/9/9 下午6:38
---
local _M = {
    _VERSION = 0.01
}
local balancer = require "ngx.balancer"
function _M.process()

    ngx.log(ngx.INFO,"阶段-"..ngx.get_phase())

    local server_ip_port = ngx.ctx.serverAddr;

    local idx = string.find(server_ip_port,":")
    local ip = string.sub(server_ip_port,0,idx - 1)
    local port = string.sub(server_ip_port,idx + 1)
    ngx.log(ngx.INFO,"路由地址"..ip .. "#" ..port)

    local ok, err = balancer.set_current_peer(ip, tonumber(port))
    if not ok then
        ngx.log(ngx.ERR, "执行异常: ", err)
        return ngx.exit(500)
    end

    local ok, err = balancer.set_timeouts(3, 2, 5)
    if not ok then
        ngx.log(ngx.ERR, "设置超时时间异常: ", err)
        return ngx.exit(500)
    end
end

_M.process();

return _M










